"""Добавлен столбец img_link в таблицу animes

Revision ID: ba0e3b0e26f3
Revises: 
Create Date: 2024-07-25 16:13:42.407703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0e3b0e26f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_link', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animes', schema=None) as batch_op:
        batch_op.drop_column('img_link')

    # ### end Alembic commands ###
